CREATE TABLE USERS(
  USER_ID VARCHAR(20) PRIMARY KEY,
  USERNAME VARCHAR(20),
  PASSWORD VARCHAR(20),
  EMAIL VARCHAR(25)
);

CREATE TABLE PROFILE(
  PROFILE_ID VARCHAR(20) PRIMARY KEY,
  USER_ID VARCHAR(20),
  PROFILE_NAME VARCHAR(20),
  BIRTHDATE DATE,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE CONTENT(
  CONTENT_ID VARCHAR(20) PRIMARY KEY,
  TITLE VARCHAR(50),
  DESCRIPTION TEXT,
  RELEASE_DATE DATE,
  DURATION INTEGER
);

CREATE TABLE WATCH_HISTORY(
  WATCH_HISTORY_ID VARCHAR(20) PRIMARY KEY,
  PROFILE_ID VARCHAR(20),
  CONTENT_ID VARCHAR(20),
  WATCH_DURATION INTEGER,
  COMPLETED BOOLEAN,
  FOREIGN KEY(PROFILE_ID) REFERENCES PROFILE(PROFILE_ID),
  FOREIGN KEY(CONTENT_ID) REFERENCES CONTENT(CONTENT_ID)
);

CREATE TABLE SUBSCRIPTION_PLAN(
  PLAN_ID VARCHAR(20) PRIMARY KEY,
  PLAN_NAME VARCHAR(20),
  PRICE INTEGER,
  QUALITY VARCHAR(15),
  MAX_PROFILES INTEGER
);

CREATE TABLE SUBSCRIPTION(
  SUBSCRIPTION_ID VARCHAR(20) PRIMARY KEY,
  USER_ID VARCHAR(20),
  PLAN_ID VARCHAR(20),
  STATUS VARCHAR(10),
  START_DATE DATE,
  END_DATE DATE,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY(PLAN_ID) REFERENCES SUBSCRIPTION_PLAN(PLAN_ID)
);

CREATE TABLE MOVIES(
  CONTENT_ID VARCHAR(20) PRIMARY KEY,
  FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(CONTENT_ID)
);


CREATE TABLE TV_SERIES(
  SERIES_ID VARCHAR(20) PRIMARY KEY,
  SERIES_NAME VARCHAR(50)
);


CREATE TABLE EPISODE(
  CONTENT_ID VARCHAR(20) PRIMARY KEY,
  SERIES_ID VARCHAR(20),
  EPISODE_NUMBER INTEGER,
  SEASON_NUMBER INTEGER,

  FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(CONTENT_ID),
  FOREIGN KEY (SERIES_ID) REFERENCES TV_SERIES(SERIES_ID)
);